import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Noto_Sans } from 'next/font/google';
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"], 
});

const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"], 
});


export const metadata: Metadata = {
  title: "Instituto Do Sorriso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${montserrat.className} ${noto.className}}`}
      >
        {children}
      </body>
    </html>
  );
}
